CREATE TABLE Comment (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    userId SMALLINT UNSIGNED NOT NULL,
    postId INT UNSIGNED NOT NULL,
    respondTo INT UNSIGNED,
    publishDate DATE NOT NULL,
    lastModificationDate DATE,
    text TEXT NOT NULL,
    FOREIGN KEY (userId) REFERENCES User(id),
    FOREIGN KEY (postId) REFERENCES Post(id),
    FOREIGN KEY (respondTo) REFERENCES Comment(id)
) ENGINE = INNODB;