CREATE TABLE IF NOT EXISTS User (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    login VARCHAR(20) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    priviledge TINYINT UNSIGNED NOT NULL DEFAULT 0,
    firtName VARCHAR(50),
    lastName VARCHAR(50),
    jobTitle VARCHAR(50),
    birthDate DATE,
    biography TEXT,
    departmentId SMALLINT UNSIGNED,
    FOREIGN KEY (departmentId) REFERENCES Department(id)
) ENGINE = INNODB;